"""Add games name and Id

Revision ID: 0e7919b2f566
Revises: 1501165bebb6
Create Date: 2024-12-28 17:53:57.805054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7919b2f566'
down_revision = '1501165bebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('game', sa.Column('difficulty', sa.String(length=20), nullable=False))
    op.drop_column('game', 'description')
    op.drop_column('game', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('title', sa.VARCHAR(length=150), nullable=False))
    op.add_column('game', sa.Column('description', sa.TEXT(), nullable=False))
    op.drop_column('game', 'difficulty')
    op.drop_column('game', 'name')
    # ### end Alembic commands ###
