"""Add games_played and math_game_score to user model

Revision ID: 1501165bebb6
Revises: 02cf2e488e1a
Create Date: 2024-12-28 17:01:27.995305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1501165bebb6'
down_revision = '02cf2e488e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('math_game_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'math_game_score')
    # ### end Alembic commands ###
